// 新闻系统配置
export const NEWS_CONFIG = {
  // 新闻影响参数
  IMPACT_RANGES: {
    WAR: { min: -500, max: 500, probability: 0.8 }, // 战争影响最大±500%
    PANDEMIC: { min: -400, max: 200, probability: 0.9 }, // 瘟疫通常负面影响
    POLITICS: { min: -150, max: 150, probability: 0.7 },
    POLICY: { min: -100, max: 100, probability: 0.6 },
    TECHNOLOGY: { min: -80, max: 200, probability: 0.5 }, // 科技通常正面
    FINANCE: { min: -120, max: 120, probability: 0.8 },
    CULTURE: { min: -50, max: 50, probability: 0.3 },
    NATURAL: { min: -200, max: 50, probability: 0.7 } // 自然灾害通常负面
  },
  
  // 每季度最大新闻数
  MAX_NEWS_PER_QUARTER: 3,
  
  // 新闻滚动速度（像素/秒）
  SCROLL_SPEED: 80,
  
  // 新闻库
  NEWS_POOL: [
    // 战争类新闻 (20条)
    { type: 'WAR', text: 'Valthara Republic declares war on neighboring Zorland Empire over disputed territories' },
    { type: 'WAR', text: 'Armed conflict erupts in the Crystalian Peninsula as three nations clash over mineral rights' },
    { type: 'WAR', text: 'Naval blockade established in the Azure Strait, disrupting major shipping routes' },
    { type: 'WAR', text: 'Mercenary forces mobilize in the Northern Highlands amid rising tensions' },
    { type: 'WAR', text: 'Peace talks collapse between Ironhold Federation and Goldmere Alliance' },
    { type: 'WAR', text: 'Aerial bombardment reported in the industrial city of Steelwatch' },
    { type: 'WAR', text: 'Refugee crisis intensifies as civilians flee from the contested Shadowlands' },
    { type: 'WAR', text: 'Military coup overthrows government in the oil-rich nation of Blackstone' },
    { type: 'WAR', text: 'Cyber warfare escalates between Techno-Republic and Digital Commonwealth' },
    { type: 'WAR', text: 'Border skirmishes intensify in the disputed Emerald Valley region' },
    { type: 'WAR', text: 'Siege of ancient fortress city Irongate enters its third month' },
    { type: 'WAR', text: 'International intervention forces deploy to the war-torn Crimson Desert' },
    { type: 'WAR', text: 'Guerrilla resistance movement gains control of strategic mountain passes' },
    { type: 'WAR', text: 'Naval battle in the Silver Sea results in significant losses on both sides' },
    { type: 'WAR', text: 'Ceasefire violations reported along the Thunderpeak Mountains border' },
    { type: 'WAR', text: 'Elite commando units conduct raids on enemy supply lines' },
    { type: 'WAR', text: 'Diplomatic immunity revoked as embassy attacks escalate tensions' },
    { type: 'WAR', text: 'Underground bunkers discovered housing weapons of mass destruction' },
    { type: 'WAR', text: 'Alliance treaty signed between three nations against common enemy' },
    { type: 'WAR', text: 'War crimes tribunal established to investigate atrocities in occupied territories' },
    
    // 瘟疫类新闻 (15条)
    { type: 'PANDEMIC', text: 'New strain of Crimson Fever spreads rapidly across the Eastern Continent' },
    { type: 'PANDEMIC', text: 'Global health emergency declared as mysterious illness affects millions' },
    { type: 'PANDEMIC', text: 'Quarantine measures imposed in major metropolitan areas worldwide' },
    { type: 'PANDEMIC', text: 'Vaccine development breakthrough announced by Meridian Pharmaceuticals' },
    { type: 'PANDEMIC', text: 'Hospital systems overwhelmed as infection rates surge in urban centers' },
    { type: 'PANDEMIC', text: 'International travel restrictions implemented to contain virus spread' },
    { type: 'PANDEMIC', text: 'Scientists identify potential animal vector for the deadly Sapphire Plague' },
    { type: 'PANDEMIC', text: 'Emergency field hospitals constructed in worst-affected regions' },
    { type: 'PANDEMIC', text: 'Antiviral treatment shows promising results in clinical trials' },
    { type: 'PANDEMIC', text: 'Mass vaccination campaign begins in the Aurora Federation' },
    { type: 'PANDEMIC', text: 'Pandemic-related supply chain disruptions affect global commerce' },
    { type: 'PANDEMIC', text: 'Mutation detected in virus strain raises concerns among health officials' },
    { type: 'PANDEMIC', text: 'Recovery rates improve with new treatment protocols' },
    { type: 'PANDEMIC', text: 'Livestock disease outbreak threatens food security in agricultural regions' },
    { type: 'PANDEMIC', text: 'WHO declares end to global health emergency after two-year crisis' },
    
    // 科技类新闻 (25条)
    { type: 'TECHNOLOGY', text: 'Quantum computing breakthrough achieved by Nexus Technologies Corporation' },
    { type: 'TECHNOLOGY', text: 'Artificial intelligence system passes advanced reasoning tests' },
    { type: 'TECHNOLOGY', text: 'Revolutionary energy storage technology unveiled by Solar Dynamics Inc.' },
    { type: 'TECHNOLOGY', text: 'Space elevator project reaches major construction milestone' },
    { type: 'TECHNOLOGY', text: 'Gene therapy treatment successfully reverses aging in clinical trials' },
    { type: 'TECHNOLOGY', text: 'Fusion power plant begins commercial operation in the Northern Territories' },
    { type: 'TECHNOLOGY', text: 'Holographic communication network launches worldwide service' },
    { type: 'TECHNOLOGY', text: 'Autonomous vehicle fleet deployment exceeds safety expectations' },
    { type: 'TECHNOLOGY', text: 'Brain-computer interface allows paralyzed patients to control devices' },
    { type: 'TECHNOLOGY', text: 'Vertical farming technology increases crop yields by 300%' },
    { type: 'TECHNOLOGY', text: 'Cryptocurrency mining operation discovers new consensus algorithm' },
    { type: 'TECHNOLOGY', text: 'Robotic workforce automation reaches 50% in manufacturing sector' },
    { type: 'TECHNOLOGY', text: 'Virtual reality platform creates immersive educational experiences' },
    { type: 'TECHNOLOGY', text: 'Biotechnology company develops synthetic blood substitute' },
    { type: 'TECHNOLOGY', text: 'Supersonic passenger aircraft completes maiden commercial flight' },
    { type: 'TECHNOLOGY', text: 'Nanotechnology breakthrough enables molecular-level manufacturing' },
    { type: 'TECHNOLOGY', text: 'Wireless power transmission technology eliminates need for cables' },
    { type: 'TECHNOLOGY', text: 'Advanced materials research produces self-healing construction components' },
    { type: 'TECHNOLOGY', text: 'Drone delivery network expands to serve remote mountainous regions' },
    { type: 'TECHNOLOGY', text: 'Machine learning algorithm predicts natural disasters with 95% accuracy' },
    { type: 'TECHNOLOGY', text: 'Renewable energy grid achieves 100% efficiency in pilot program' },
    { type: 'TECHNOLOGY', text: 'Telepresence technology enables remote surgery across continents' },
    { type: 'TECHNOLOGY', text: 'Blockchain technology revolutionizes supply chain transparency' },
    { type: 'TECHNOLOGY', text: 'Smart city infrastructure project reduces energy consumption by 40%' },
    { type: 'TECHNOLOGY', text: 'Cybersecurity system detects and prevents 99.9% of malware attacks' },
    
    // 政策类新闻 (20条)
    { type: 'POLICY', text: 'Central Bank of Silvermoon announces new monetary policy framework' },
    { type: 'POLICY', text: 'Trade tariffs reduced between Goldshore Union and Crystal Coast Alliance' },
    { type: 'POLICY', text: 'Environmental protection laws strengthened in the Greenland Federation' },
    { type: 'POLICY', text: 'Universal basic income pilot program launched in the Progressive States' },
    { type: 'POLICY', text: 'Corporate tax rates adjusted to stimulate economic growth' },
    { type: 'POLICY', text: 'Immigration policy reforms ease restrictions for skilled workers' },
    { type: 'POLICY', text: 'Healthcare system overhaul promises universal coverage' },
    { type: 'POLICY', text: 'Education funding increased by 25% in the Knowledge Republic' },
    { type: 'POLICY', text: 'Infrastructure investment plan allocates billions for modernization' },
    { type: 'POLICY', text: 'Financial regulations tightened following banking sector scandals' },
    { type: 'POLICY', text: 'Energy independence initiative promotes renewable resource development' },
    { type: 'POLICY', text: 'Labor laws updated to protect gig economy workers' },
    { type: 'POLICY', text: 'Housing affordability program provides subsidies for first-time buyers' },
    { type: 'POLICY', text: 'Digital privacy legislation grants citizens greater data control' },
    { type: 'POLICY', text: 'Agricultural subsidies restructured to support sustainable farming' },
    { type: 'POLICY', text: 'Transportation policy shift prioritizes public transit development' },
    { type: 'POLICY', text: 'Pension system reforms ensure long-term sustainability' },
    { type: 'POLICY', text: 'Small business support package includes tax incentives and grants' },
    { type: 'POLICY', text: 'International trade agreement signed with emerging market nations' },
    { type: 'POLICY', text: 'Research and development tax credits expanded for innovation sectors' },
    
    // 政治类新闻 (20条)
    { type: 'POLITICS', text: 'Presidential election results trigger celebrations in the Democratic Republic of Azuria' },
    { type: 'POLITICS', text: 'Coalition government formed after months of political negotiations' },
    { type: 'POLITICS', text: 'Corruption scandal rocks the ruling party in the Merchant Kingdoms' },
    { type: 'POLITICS', text: 'Opposition leader calls for vote of no confidence in parliament' },
    { type: 'POLITICS', text: 'Constitutional referendum passes with narrow majority' },
    { type: 'POLITICS', text: 'Political protests demanding electoral reforms sweep across major cities' },
    { type: 'POLITICS', text: 'Diplomatic crisis erupts over ambassador expulsion incident' },
    { type: 'POLITICS', text: 'New political party gains significant support in regional elections' },
    { type: 'POLITICS', text: 'Supreme Court ruling overturns controversial legislation' },
    { type: 'POLITICS', text: 'International sanctions imposed on authoritarian regime' },
    { type: 'POLITICS', text: 'Peace treaty signed ending decades-long territorial dispute' },
    { type: 'POLITICS', text: 'Parliamentary session suspended amid heated budget debates' },
    { type: 'POLITICS', text: 'Electoral commission announces investigation into voting irregularities' },
    { type: 'POLITICS', text: 'Foreign minister resigns following diplomatic scandal' },
    { type: 'POLITICS', text: 'Regional autonomy agreement reached after years of negotiations' },
    { type: 'POLITICS', text: 'Political asylum granted to refugees from neighboring authoritarian state' },
    { type: 'POLITICS', text: 'Cabinet reshuffle brings new faces to key ministerial positions' },
    { type: 'POLITICS', text: 'International summit addresses global cooperation challenges' },
    { type: 'POLITICS', text: 'Judicial reform package aims to improve court system efficiency' },
    { type: 'POLITICS', text: 'Transparency laws require public disclosure of political donations' },
    
    // 金融类新闻 (30条)
    { type: 'FINANCE', text: 'Stormwind Financial Group announces record quarterly profits' },
    { type: 'FINANCE', text: 'Cryptocurrency exchange Dragonhoard reports security breach affecting millions' },
    { type: 'FINANCE', text: 'Meridian Bank merger creates largest financial institution in the region' },
    { type: 'FINANCE', text: 'Interest rates cut by 0.5% to stimulate economic recovery' },
    { type: 'FINANCE', text: 'Initial public offering of Phoenix Technologies exceeds expectations' },
    { type: 'FINANCE', text: 'Corporate bond defaults surge amid economic uncertainty' },
    { type: 'FINANCE', text: 'Venture capital funding for startups reaches all-time high' },
    { type: 'FINANCE', text: 'Real estate market correction sees property values decline 15%' },
    { type: 'FINANCE', text: 'Commodity prices soar following supply chain disruptions' },
    { type: 'FINANCE', text: 'Insurance giant Fortress Holdings faces liquidity crisis' },
    { type: 'FINANCE', text: 'Stock market volatility reaches extreme levels amid geopolitical tensions' },
    { type: 'FINANCE', text: 'Central bank digital currency pilot program shows promising results' },
    { type: 'FINANCE', text: 'Hedge fund Shadowmere Capital reports 300% annual returns' },
    { type: 'FINANCE', text: 'Banking sector stress tests reveal vulnerabilities in loan portfolios' },
    { type: 'FINANCE', text: 'Fintech startup Swiftpay revolutionizes cross-border payments' },
    { type: 'FINANCE', text: 'Pension fund crisis threatens retirement security for millions' },
    { type: 'FINANCE', text: 'Credit rating agency downgrades sovereign debt of struggling nation' },
    { type: 'FINANCE', text: 'Algorithmic trading system malfunction causes market flash crash' },
    { type: 'FINANCE', text: 'Green bonds market expands as sustainable investing gains momentum' },
    { type: 'FINANCE', text: 'Money laundering investigation targets major international bank' },
    { type: 'FINANCE', text: 'Derivatives market reaches $500 trillion in notional value' },
    { type: 'FINANCE', text: 'Robo-advisor platform manages over $100 billion in client assets' },
    { type: 'FINANCE', text: 'Financial crisis in emerging markets spreads to developed economies' },
    { type: 'FINANCE', text: 'Blockchain technology adoption accelerates in traditional banking' },
    { type: 'FINANCE', text: 'Private equity firm acquires struggling retail chain for restructuring' },
    { type: 'FINANCE', text: 'Currency manipulation allegations strain international trade relations' },
    { type: 'FINANCE', text: 'Microfinance institutions expand access to credit in rural areas' },
    { type: 'FINANCE', text: 'Sovereign wealth fund diversifies portfolio with technology investments' },
    { type: 'FINANCE', text: 'Financial inclusion initiative brings banking services to underserved populations' },
    { type: 'FINANCE', text: 'Regulatory sandbox allows fintech experimentation with relaxed oversight' },
    
    // 人文类新闻 (15条)
    { type: 'CULTURE', text: 'Ancient artifacts discovered in archaeological dig at Moonstone Ruins' },
    { type: 'CULTURE', text: 'International arts festival showcases diverse cultural expressions' },
    { type: 'CULTURE', text: 'Renowned musician from Harmony Islands wins global music award' },
    { type: 'CULTURE', text: 'Literary masterpiece translated into 50 languages worldwide' },
    { type: 'CULTURE', text: 'Cultural heritage site granted protection status by international body' },
    { type: 'CULTURE', text: 'Traditional crafts revival movement gains momentum among young artisans' },
    { type: 'CULTURE', text: 'Documentary film exposes social issues in marginalized communities' },
    { type: 'CULTURE', text: 'Language preservation project records endangered dialects' },
    { type: 'CULTURE', text: 'Cultural exchange program strengthens ties between distant nations' },
    { type: 'CULTURE', text: 'Museum exhibition breaks attendance records with innovative displays' },
    { type: 'CULTURE', text: 'Street art movement transforms urban landscapes in major cities' },
    { type: 'CULTURE', text: 'Culinary fusion trend blends traditional recipes with modern techniques' },
    { type: 'CULTURE', text: 'Dance performance celebrates unity among diverse ethnic groups' },
    { type: 'CULTURE', text: 'Philosophical movement questions traditional values in modern society' },
    { type: 'CULTURE', text: 'Cultural diplomacy initiative promotes understanding through arts exchange' },
    
    // 自然灾害类新闻 (15条)
    { type: 'NATURAL', text: 'Magnitude 7.8 earthquake strikes the Crimson Mountain region' },
    { type: 'NATURAL', text: 'Volcanic eruption forces evacuation of 100,000 residents from Firestone Island' },
    { type: 'NATURAL', text: 'Severe flooding devastates agricultural areas in the Greenriver Valley' },
    { type: 'NATURAL', text: 'Category 5 hurricane approaches the Sapphire Coast with destructive winds' },
    { type: 'NATURAL', text: 'Prolonged drought threatens water supply in the Desert Kingdoms' },
    { type: 'NATURAL', text: 'Wildfire spreads rapidly through ancient forests of the Whisperwood Region' },
    { type: 'NATURAL', text: 'Tsunami warning issued following underwater seismic activity' },
    { type: 'NATURAL', text: 'Blizzard conditions paralyze transportation in the Northern Territories' },
    { type: 'NATURAL', text: 'Landslide blocks major highway through the Stormcrest Mountains' },
    { type: 'NATURAL', text: 'Extreme heatwave breaks temperature records across multiple regions' },
    { type: 'NATURAL', text: 'Tornado outbreak causes widespread destruction in the Windswept Plains' },
    { type: 'NATURAL', text: 'Avalanche buries mountain village in the Frozen Peaks region' },
    { type: 'NATURAL', text: 'Coral bleaching event affects marine ecosystems in tropical waters' },
    { type: 'NATURAL', text: 'Meteor shower creates spectacular display but causes communication disruptions' },
    { type: 'NATURAL', text: 'Solar storm generates beautiful auroras while disrupting satellite systems' }
  ]
}; 